### ISSUE TITLE
How to do you export your notes also as plain text?

### ISSUE THREAD

**Issue by evandrocoan** [CNG/anki-decks#2]
Hi. I have been using CrowdAnki to version my notes, but it is difficult to see the git diff from it. Reading your comment:
> My half solution there has been to simultaneously export the plain text notes and place them alongside the JSON.
> https://github.com/Stvad/CrowdAnki/issues/2#issuecomment-314582943

Do you manually export your decks as plain text, or can CrowdAnki be configured to do this for you?

Related to: https://github.com/Stvad/CrowdAnki/issues/38

**Comment by evandrocoan** [comment]
I see I can convert the final json back to yaml, which is 100% more readable: 
```python
import sys
import json
import yaml

# python3 -m pip install pyyaml
yaml.dump(json.load(open("deck.json")), open('deck.yml', 'w'), default_flow_style=False, allow_unicode=True)
```

**Comment by CNG** [comment]
Hi there,

I believe I was using an export notes as TSV or some similar option in the standard Anki binary. I don't remember (hah) exactly as I haven't used Anki on computer in years. I went overboard with customizing the HTML and JS of my deck templates, and of course something broke with an Android update years ago, and I didn't have time to debug it at the time and then my Anki use fell off. Starting a new, simpler setup is still on my list. :-)

**Comment by evandrocoan** [comment]
I see. Thanks for answering. For now, I managed to create this script to convert my decks back and forth from .yaml to .json. Then, I can ignore the .json files and work only with .yaml files, and still use CrowdAnki as the conversion does not loose anything: https://github.com/Stvad/CrowdAnki/issues/38#issuecomment-1374978754

**Comment by CNG** [comment]
Thanks very much for that!
